### ISSUE TITLE
% truncated at 100, % incorrect 

### ISSUE THREAD

**Issue by sdetweil** [btastic/MMM-octoprint#3]
![Screenshot at 2023-05-30 08-57-55](https://github.com/btastic/MMM-octoprint/assets/1498142/a5f5a25a-e4bc-4a12-a6a7-67edd5da4f6f)

also, really not 100% yet, progress plugin says 99
![Screenshot at 2023-05-30 09-00-36](https://github.com/btastic/MMM-octoprint/assets/1498142/caa65057-ed7c-4d74-86ca-cb2399ef3ae2)

so I think the round in the template  shouldn't be used

**Comment by btastic** [comment]
% cutoff fixed with https://github.com/btastic/MMM-octoprint/commit/25fd23a0440caa6469d4ea36dda6506bb13bebea
removed rounding with https://github.com/btastic/MMM-octoprint/commit/62a0a3690a969b9d3a484d95733efe4a215388df
